import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const Windows98Colors = () => {
  const colors = [
    { name: 'Background (Desktop)', tailwind: 'bg-teal-600', hex: '#008080' },
    { name: 'Window Background', tailwind: 'bg-gray-200', hex: '#C0C0C0' },
    { name: 'Window Title Bar Active', tailwind: 'bg-blue-800', hex: '#000080' },
    { name: 'Window Title Bar Text', tailwind: 'text-white', hex: '#FFFFFF' },
    { name: 'Window Title Bar Inactive', tailwind: 'bg-gray-600', hex: '#808080' },
    { name: 'Button Face', tailwind: 'bg-gray-300', hex: '#C0C0C0' },
    { name: 'Button Shadow', tailwind: 'bg-gray-700', hex: '#808080' },
    { name: 'Button Text', tailwind: 'text-black', hex: '#000000' },
    { name: 'Selected Item', tailwind: 'bg-blue-800', hex: '#000080' },
    { name: 'Selected Text', tailwind: 'text-white', hex: '#FFFFFF' }
  ];
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-teal-600">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
